# Generated by Django 5.1.6 on 2025-03-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_document_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PHY', 'Physics'), ('MATH', 'Mathematics'), ('BIO', 'Biology')], max_length=4)),
                ('difficulty', models.PositiveIntegerField()),
                ('questions', models.ManyToManyField(to='learning.question')),
            ],
        ),
    ]
